### ISSUE TITLE
Possible problem in the build system

### ISSUE THREAD

**Issue by jgsabatini** [resurrecting-open-source-projects/scrot#18] opened 2019-06-23 03:27 UTC
When ./configure is executed it returns two errors:

`./configure: line 2525: syntax error near unexpected token 'src/scrot_config.h'
./configure: line 2525: 'AX_PREFIX_CONFIG_H(src/scrot_config.h)'`

The solution is create the scrot_config.h with definition of SCROT_PACKAGE and SCROT_VERSION, but I believe this file should either exist in the repository or be auto generated by the build system.

**Comment by eribertomota** [comment] 2019-06-23 08:15
Hi @jgsabatini 

It is not a bug. As described in README file, you need autoconf-archive[1] to build. On Debian you can do 'apt-get install autoconf-archive'.

[1] https://www.gnu.org/software/autoconf-archive/

I am closing this bug. Feel free to reopen if needed.

Regards,

Eriberto

**Closed by eribertomota** 2019-06-23 08:15 UTC
